file_format: "1"
id: cygnus
name: Cygnus
type: shield
url: https://github.com/juhakaup/keyboards/tree/main/Cygnus%20v1.0
requires: [pro_micro]
exposes: []
features:
  - keys
  - studio
siblings:
  - cygnus_left
  - cygnus_right
