manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: carrefinho
      url-base: https://github.com/carrefinho
    - name: mike1808
      url-base: https://github.com/mike1808
    - name: janpfischer
      url-base: https://github.com/janpfischer
    - name: m165437
      url-base: https://github.com/M165437
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # - name: zmk-dongle-screen
    #   remote: janpfischer
    #   revision: upgrade-4.1
    # - name: nice-view-gem
    #   remote: m165437
    #   revision: main
    - name: nice-view-gem
      remote: mike1808
      revision: fix/zmk-endpoint-api
    - name: prospector-zmk-module
      remote: mike1808
      revision: fix/new-status-screan-zmk-refactor
  self:
    path: config
